{
 "title": "COCHE",
 "time": { "from": "2024-04-20T11:37:16.313Z", "to": "2024-04-20T11:41:48.005Z" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"vin\",\n    predicate: (r) => true,\n    start: -60d\n)"
   },
   { "name": "measurement_source", "query": "${VAR_MEASUREMENT_SOURCE}" }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"velocidad\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"revoluciones_por_minuto\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura_refrigerante\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"presion_absoluta_colector_admisión\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carga_motor\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura_aire_colector_admisión\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    },
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"caudal_aire_sensor_maf\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "GPS",
   "type": "geomap",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitud\" or r[\"_field\"] == \"longitud\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Velocidad del vehículo (km/h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"velocidad\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Revoluciones por minuto (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"revoluciones_por_minuto\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura del refrigerante (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura_refrigerante\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura aire colector admisión (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura_aire_colector_admisión\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Caudal aire sensor MAF (g/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"caudal_aire_sensor_maf\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Presión absoluta colector admisión (kpA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"presion_absoluta_colector_admisión\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Carga del motor (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_source}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carga_motor\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Alertas", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 } }
 ]
}