{
 "title": "COCHE",
 "time": { "from": "2024-04-15T17:04:42.696Z", "to": "2024-04-15T17:06:45.266Z" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"vin\",\n    predicate: (r) => true,\n    start: -10d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Velocidad del vehículo (km/h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Revoluciones por minuto (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura del refrigerante (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Presión absoluta colector admisión (kpA)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"intake_manifold_absolute_pressure\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Caudal aire sensor MAF (g/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"air_flow_speed_maf\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Carga del motor (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"motor_load\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura aire colector admisión (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"intake_manifold_air_temperature\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GPS",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"coche2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"${VIN}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}