{
 "title": "COCHE",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SPEED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem1\" and\r\n    r._field == \"speed\"\r\n  )"
    }
   ]
  },
  {
   "title": "SPEED",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem1\" and\r\n    r._field == \"speed\"\r\n  )"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem1\" and\r\n    r._field == \"rpm\"\r\n  )"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem1\" and\r\n    r._field == \"rpm\"\r\n  )"
    }
   ]
  },
  {
   "title": "TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem1\" and\r\n    r._field == \"temp\"\r\n  )"
    }
   ]
  },
  {
   "title": "TEMP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"android\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem1\" and\r\n    r._field == \"temp\"\r\n  )"
    }
   ]
  }
 ]
}